### ISSUE TITLE
Fact dimension modeling

### ISSUE THREAD

**Issue by AdautoDCJunior** [AdautoDCJunior/alura-log#6]
### Subtasks
- [x] https://github.com/AdautoDCJunior/alura-log/issues/5
- [x] Entity relationship diagrams (DER)
- [x] Entity relationship models (MER)

**Comment by AdautoDCJunior** [comment]
Modeling completed, here's the [link](https://drive.google.com/file/d/18DKRYP1Fei0JF6OmTtr_M9Br0EmMI92m/view?usp=sharing) to the model (Pages 7, 8 and 9).
